logging:
  file: certificateGenerator
  path: /apps/OpsERA/logs/components/certificate-generator
server:
  port: 8055
spring:
  application:
    name: certificate-generator
    description: Service to monitor and alert
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
pipeline:
  config:
    baseurl: ${opsera.config.baseurl}/api/pipeline

---

spring:
  profiles: kubernetes

opsera:
  config:
    baseurl: ${OPSERA_API_SERVICE_URL:http://opsera-apigateway.microservices.svc.cluster.local:9091}
